[package]
name = "casual-szu-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Keaton Jiang <jiang131072@gmail.com>"]
license = "MIT"
description = "A template for SZU course reports."

homepage = "https://typst.app/universe/package/report-szu"
repository = "https://github.com/jiang131072/report-szu-typst"
keywords = ["SZU", "Shenzhen University", "report"]
categories = ["report"]
disciplines = []
exclude = []

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"